version: '2'
services:
    pichangas-app:
        image: pichangas
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pichangasinstance.cqwwzgdcitgs.us-east-2.rds.amazonaws.com:3306/pichangas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_DATASOURCE_USERNAME=userpichangas
            - SPRING_DATASOURCE_PASSWORD=123Pichanga
        ports:
            - 8080:8080
    pichangas-mysql:
        extends:
            file: mysql.yml
            service: pichangas-mysql
